name: pnet
channels:
  - plotly
  - defaults
dependencies:
  - pip=18.1
  - enum34=1.1.6
  - futures=3.3.0
  - h5py=2.9.0l.c
  - hdf5=1.10.4
  - imageio=2.6.1
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - markdown=3.1.1
  - numpy=1.16.6
  - pandas=0.23.4
  - plotly=4.5.4
  - protobuf=3.11.2
  - python=2.7.15
  - pyyaml=5.1.1
  - scikit-image=0.14.2
  - scikit-learn=0.20.1
  - scipy=1.1.0
  - subprocess32=3.5.4
  - tensorboard=1.12.2
  - tensorflow=1.12.0
  - yaml=0.1.7
  - plotly-orca=1.3.1
  - pip:
      - adjusttext==0.7.3
      - lifelines==0.19.5
      - matplotlib==2.2.4
      - psutil==5.8.0
      - networkx==2.2
      - pyvis==0.1.7.0
      - requests==2.23.0
      - rope==0.18.0
      - seaborn==0.9.1
      - toml==0.10.2
      - upsetplot==0.4.0
      - urllib3==1.25.8
      - xlrd==0.9.0
